spring:
  shardingsphere:
    # 配置数据源
    datasource:
      names: master1,slave0
      master1:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3339/test?characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: root@123
      slave0:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3340/test?characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
        password: root@123
    sharding:
      # 读写分离
      master-slave-rules:
        ds:
          master-data-source-name: master1
          slave-data-source-names: slave0
      # 水平分表
      tables:
        t_order:
          actual-data-nodes: ds.t_order_$->{0..2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: t_order_$->{id % 3}
    # 开启SQL显示，默认值: false，注意：仅配置读写分离时不会打印日志
    props:
      sql:
        show: true
#  main:
#    allow-bean-definition-overriding: true

#logging:
#  level:
#    club:
#      wyc1856:
#        sharding:
#          mapper: debug
